//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Kurs.java
//  @ Date : 22.05.2026
//  @ Author : 
//
//




public class Kurs {
	private String id;
	private String tytul;
	private String haslo;
	private ArrayList<Uzytkownik> uzytkownicy;
	private ArrayList<Material> materialy;
	private ArrayList<Test> testy;
	private String sylabus;
	private boolean widocznosc;
	public void Kurs(String id, String tytul, String haslo) {
	
	}
	
	public void zmienHaslo() {
	
	}
	
	public void dodajMaterialy(String plik, String tytul) {
	
	}
	
	public void usunMaterialy(String tytul) {
	
	}
	
	public void wyswietlMaterialy() {
	
	}
	
	public void dodajTest(String plik, String tytul, LocalDate datakonca) {
	
	}
	
	public void ocenTest(String login, Float ocena) {
	
	}
	
	public void wyswietlTesty() {
	
	}
	
	public void zmienWidocznoscMaterialu() {
	
	}
	
	public void setSylabus() {
	
	}
}
