//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Material.java
//  @ Date : 22.05.2026
//  @ Author : 
//
//




public class Material {
	private String plik;
	private String tytul;
	private LocalDate data;
	private boolean widocznosc;
	public void Material(String plik, String tytul) {
	
	}
	
	public String getPlik() {
	
	}
	
	public String getTytul() {
	
	}
	
	public LocalDate getData() {
	
	}
	
	public boolean getWidocznosc() {
	
	}
	
	public void zmienWidocznosc() {
	
	}
}
