//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SystemZarzadzania.java
//  @ Date : 22.05.2026
//  @ Author : 
//
//




public class SystemZarzadzania {
	private ArrayList<Kurs> kursy;
	private ArrayList<Uzytkownik> uzytkownicy;
	private Kurs obecnyKurs;
	private BazaLogowan bazaLogowan;
	public void SystemZarzadzania() {
	
	}
	
	public void zmienHaslo() {
	
	}
	
	public void dodajMaterialy(String plik, String tytul) {
	
	}
	
	public void usunMaterialy(String tytul) {
	
	}
	
	public void wyswietlMaterialy() {
	
	}
	
	public void dodajTest(String plik, String tytul, LocalDate datakonca) {
	
	}
	
	public void ocenTest(String login, Float ocena) {
	
	}
	
	public void wyswietlTesty() {
	
	}
	
	public void zmienWidocznoscMaterialu() {
	
	}
	
	public void setSylabus() {
	
	}
	
	public void zmienKurs() {
	
	}
}
