//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Test.java
//  @ Date : 22.05.2026
//  @ Author : 
//
//




public class Test {
	private String plik;
	private String tytul;
	private LocalDate dataWyslania;
	private LocalDate dataKonca;
	private HashMap<String, Float> oceny;
	private HashMap<String, String> rozwiazania;
	private boolean widocznosc;
	public void Test(String plik, String tytul, LocalDate dataKonca) {
	
	}
	
	public void ocen(String login, Object ocena Float) {
	
	}
	
	public String getPlik() {
	
	}
	
	public String getTytul() {
	
	}
	
	public LocalDate getDataWyslania() {
	
	}
	
	public LocalDate getDataKonca() {
	
	}
	
	public String getOceny() {
	
	}
	
	public Float getOcena() {
	
	}
	
	public boolean getWidcznosc() {
	
	}
	
	public void zmienWidocznosc() {
	
	}
}
