//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.java
//  @ Date : 22.05.2026
//  @ Author : 
//
//




public class Wykladowca extends Uzytkownik {
	private ArrayList<Kurs> kursy;
	public void Wykladowca() {
	
	}
	
	public void utworzKurs(String nazwa, String haslo) {
	
	}
	
	public void zmienSylabus(String link) {
	
	}
	
	public void dodajMaterialy(String plik, String tytul) {
	
	}
	
	public String): void usunMaterialyplik() {
	
	}
	
	public void sprawdzMaterialy() {
	
	}
	
	public void dodajTest(String plik, String tytul, LocalDate datakonca) {
	
	}
	
	public void sprawdzOceny() {
	
	}
	
	public void sprawdzSylabus() {
	
	}
}
