//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BazaLogowan.java
//  @ Date : 22.05.2026
//  @ Author : 
//
//




public class BazaLogowan {
	private String plik;
	public void BazaLogowan(String plik) {
	
	}
	
	public boolean sprawdzWPliku(String login, String haslo) {
	
	}
	
	public void zapiszDoPliku() {
	
	}
	
	public boolean zarejestrujUzytkownika(String login, String haslo) {
	
	}
	
	public boolean usunUzytkownika(String login) {
	
	}
	
	public boolean zmienHaslo(String login, String haslo, String noweHaslo) {
	
	}
}
