//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BazaLogowan.java
//  @ Date : 22.05.2026
//  @ Author : 
//
//


import java.util.Optional;

public class BazaLogowan {
	private String plik;
	public BazaLogowan(String plik) {
		this.plik = plik;
	}
	
	public Optional<Uzytkownik> sprawdzWPliku(String login, String haslo) {

	}
	
	public void zapiszDoPliku() {
	
	}
	
	public boolean zarejestrujUzytkownika(String login, String haslo) {
	
	}
	
	public boolean usunUzytkownika(String login) {
	
	}
	
	public boolean zmienHaslo(String login, String haslo, String noweHaslo) {
	
	}
}
