//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.java
//  @ Date : 22.05.2026
//  @ Author : 
//
//




public class Uzytkownik {
	private String login;
	public void Uzytkownik(String login, String haslo) {
	
	}
	
	public boolean zalogujSie(String login, String haslo) {
	
	}
	
	public boolean zmienHaslo(String login, String haslo, String noweHaslo) {
	
	}
}
